<a href="https://colab.research.google.com/github/salonikumari17898/Python-Data-Analytics/blob/main/Pandas_Series.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Series using read_csv

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
# with one col
import pandas as pd

df = pd.read_csv('/content/subs (1).csv')

series = df.squeeze("columns")

type(series)

pandas.core.series.Series

In [ ]:
subs = pd.read_csv('/content/subs (1).csv').squeeze("columns")
subs

0       48
1       57
2       40
3       43
4       44
      ...
360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, Length: 365, dtype: int64

In [ ]:

import pandas as pd

vk = pd.read_csv(
    '/content/kohli_ipl.csv',
    index_col='match_no'
)

vk

          runs
match_no
1            1
2           23
3           13
4           12
5            1
...        ...
211          0
212         20
213         73
214         25
215          7

[215 rows x 1 columns]

In [ ]:
import pandas as pd

movies = pd.read_csv(
    '/content/bollywood.csv',
    index_col='movie'
)

movies

                                                  lead
movie
Uri: The Surgical Strike                 Vicky Kaushal
Battalion 609                              Vicky Ahuja
The Accidental Prime Minister (film)       Anupam Kher
Why Cheat India                          Emraan Hashmi
Evening Shadows                       Mona Ambegaonkar
...                                                ...
Hum Tumhare Hain Sanam                  Shah Rukh Khan
Aankhen (2002 film)                   Amitabh Bachchan
Saathiya (film)                           Vivek Oberoi
Company (film)                              Ajay Devgn
Awara Paagal Deewana                      Akshay Kumar

[1500 rows x 1 columns]

In [ ]:
#Series method
#head and tail
subs.head()

0    48
1    57
2    40
3    43
4    44
Name: Subscribers gained, dtype: int64

In [ ]:
subs.tail()

360    231
361    226
362    155
363    144
364    172
Name: Subscribers gained, dtype: int64

In [ ]:
vk.head(3)

          runs
match_no
1            1
2           23
3           13

In [ ]:
#sample
movies.sample(10)

                                             lead
movie
Magic Magic 3D                      Sooraj Balaji
Love U...Mr. Kalakaar!             Tusshar Kapoor
Eight: The Power of Shani                Raj Tara
Gori Tere Pyaar Mein                   Imran Khan
Kuch Naa Kaho              Aishwarya Rai Bachchan
Titoo MBA                          Nishant Dahiya
Chal Pichchur Banate Hain          Sagar Bhangade
Gattu                               Naresh Sharma
Don Muthu Swami                Mithun Chakraborty
Life Mein Kabhie Kabhiee         Aftab Shivdasani